import { useState } from "react";

import styles from "@/styles/Home.module.css";
import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import { Loader, useLoader, WithLoader } from "react-loader-ts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app-container">
        <header>
          <h1>React Loader TS Demo</h1>
          <p>
            Demonstrating Loader & WithLoader components with dark mode support
          </p>
          <button
            onClick={() => setIsLoading((prev) => !prev)}
            className="toggle-button"
          >
            {isLoading ? "Stop Loading" : "Start Loading"}
          </button>
        </header>

        <section className="loader-examples">
          <h2>Loader component</h2>
          <div className="loader-row">
            <div>
              <p>Default (dots)</p>
              <Loader variant="dots" />
            </div>
            <div>
              <p>Circle Dots variant</p>
              <Loader variant="circle-dots" />
            </div>
            <div>
              <p>Inline Loader</p>
              <span>
                Loading
                <Loader variant="dots" inline />
              </span>
            </div>
          </div>
        </section>

        <section className="loader-examples">
          <h2>WithLoader component</h2>
          <WithLoader isLoading={isLoading} variant="circle-dots">
            <div className="content-box">
              <p>This content is shown only when not loading.</p>
              <p>
                Toggle the button above to simulate loading state and see the
                loader replacing this content.
              </p>
            </div>
          </WithLoader>
        </section>
      </div>
    </>
  );
}
